'use strict';
var express = require("express");
var commonService = require('../services/apiServices/apiCommonService');
var bodyParser = require('body-parser');
var config = require('../config');
var jwt = require('jsonwebtoken');

var multer = require('multer');
var path = require('path');


var secretKey = config.secretKey;

var api = express.Router();
//api.use(bodyParser.json());
// api.use(bodyParser.urlencoded({
// extended: false
// }));


const fs = require('fs');
//var upload = multer({ dest: 'uploads/' }); 
api.use(bodyParser.json());


// const DIR = 'public/uploads';
/*
var multer  = require('multer');
var upload = multer({ dest: '/uploads/' }); //setting the default folder for multer//other imports and code will go hereapp.post('/upload',upload.single('fileData'), (req, res,next) => {

    api.post('/upload',upload.single('profileImage'), (req, res,next) => {
        console.log(req.files);//this will be automatically set by multer
        console.log(req.body);
        //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    //     fs.readFile(req.files.path,(err, contents)=> {
    //      if (err) {
    //      console.log('Error: ', err);
    //     }else{
    //      console.log('File contents ',contents);
    //     }
    //    });
    res.send({'req.files':req.files});
      });

*/

  // Edit Profile Image
  api.post('/upload', function (req, res) {
      console.log('files',req)
    commonService.uploadUserImageService(req.body, req.files, function (result) {
      res.send(result);
    })
  });


// api.post('/upload', function (req, res) {
//     console.log(req.files)

//     if (!req.files) {

//         console.log("No file received");
//         return res.send({
//             success: false,
//             STATUSCODE: 4200,
//             message: "Please Provide User Profile Image",
//             response: {'REQuest file': req.file,'REQuest body': req.body,'REQuest header': req.headers }
//         });

//     } else {

//         console.log('file received successfully');
//         var adminData = req.body;
//         commonService.uploadUserImageService(req.body,req.files, function (response) {
//         res.send(response);
//         });
    
//     }
// });


api.post('/adminSignup', function (req, res) {
    var adminData = req.body;
    commonService.adminSignup(adminData, function (response) {
         res.send(response);
    });
});
api.post('/adminLogin', function (req, res) {
    var adminData = req.body;
    commonService.adminLogin(adminData, function (response) {
         res.send(response);
    });
});



//#region for user management

//Change password
api.post('/changePassword', function (req, res) {
    console.log('req.headers---->',req.headers.authtoken)
    var token = req.body.authtoken || req.params.authtoken || req.headers.authtoken;

    commonService.changePassword(req.body,token, function (response) {
        res.send(response);
    });
});

//verify Changed Email 
api.post('/verifyChangedEmail', function (req, res) {
    //console.log('req.headers---->',req.headers.authtoken)

    commonService.verifyChangedEmail(req.body, function (response) {
        res.send(response);
    });
});



//Forgot password
api.post('/forgotPassword', function (req, res) {
    commonService.forgotPassword(req.body, function (response) {
        res.send(response);
    });
});

api.post('/userLogin', function (req, res) {
    var userData = req.body;
    commonService.userLogin(userData, function (response) {
         res.send(response);
    });
});

api.post('/addUser', function (req, res) {
    var adminData = req.body;
    commonService.addUserService(adminData, function (response) {
          res.send(response);
    });
});

api.post('/chat', function (req, res) {
    var adminData = req.body;
    commonService.chatService(adminData, function (response) {
          res.send(response);
    });
});

api.post('/listUser', function (req, res) {
    var adminData = req.query;
    console.log('req.body----->',req.body)

    commonService.listUserService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/editUser', function (req, res) {

    var adminData = req.body;
    commonService.editUserService(req.body,req.files, function (response) {
    res.send(response);
    });

})

api.post('/deleteUser', function (req, res) {
    var adminData = req.body;
    commonService.deleteUserService(adminData, function (response) {
        res.send(response);
    });
})

api.get('/get-all-user', function (req, res) {
    var adminData = req.body;
    commonService.getAllUserService(adminData, function (response) {
         res.send(response);
    });
})        

//#endregion



//#region for Category management


api.post('/addCategory', function (req, res) {
    var adminData = req.body;
    commonService.addCategoryService(adminData, function (response) {
          res.send(response);
    });
});

api.get('/listCategory', function (req, res) {
    var adminData = req.query;
    commonService.listCategoryService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/editCategory', function (req, res) {
    var adminData = req.body;
    commonService.editCategoryService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/deleteCategory', function (req, res) {
    var adminData = req.body;
    commonService.deleteCategoryService(adminData, function (response) {
        res.send(response);
    });
})

api.post('/get-all-category', function (req, res) {
    var adminData = req.body;
    commonService.getAllCategoryService(adminData, function (response) {
         res.send(response);
    });
})        

//#endregion


//#region for Field management


api.post('/addField', function (req, res) {
    var adminData = req.body;
    commonService.addFieldService(adminData, function (response) {
          res.send(response);
    });
});

api.get('/listField', function (req, res) {
    var adminData = req.query;
    commonService.listFieldService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/editField', function (req, res) {
    var adminData = req.body;
    commonService.editFieldService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/deleteField', function (req, res) {
    var adminData = req.body;
    commonService.deleteFieldService(adminData, function (response) {
        res.send(response);
    });
})

api.post('/get-all-field', function (req, res) {
    var adminData = req.body;
    commonService.getAllFieldService(adminData, function (response) {
         res.send(response);
    });
})        

//#endregion


//#region for AboutUs


api.post('/addAboutUs', function (req, res) {
    var adminData = req.body;
    commonService.addAboutUsService(adminData, function (response) {
          res.send(response);
    });
});

api.get('/listAboutUs', function (req, res) {
    var adminData = req.query;
    commonService.listAboutUsService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/editAboutUs', function (req, res) {
    var adminData = req.body;
    commonService.editAboutUsService(adminData, function (response) {
         res.send(response);
    });
})

api.post('/deleteAboutUs', function (req, res) {
    var adminData = req.body;
    commonService.deleteAboutUsService(adminData, function (response) {
        res.send(response);
    });
})

api.get('/get-all-aboutislam', function (req, res) {
    var adminData = req.body;
    commonService.getAllAboutUsService(adminData, function (response) {
         res.send(response);
    });
})        

//#endregion

  //verify Email
  api.post('/verifyEmail', function (req, res) {
    commonService.verifyEmail(req.body, function (response) {
      res.send(response);
    });
  });

  //verify Email Otp
  api.post('/verifyEmailOtp', function (req, res) {
    commonService.verifyEmailOtpService(req.body, function (response) {
      res.send(response);
    });
  });

    //social Login
  api.post('/socialLogin', (req, res) => {

    commonService.socialRegister(req.body, function (response) {
      res.send(response);
    });
  });

  //Add edit Notification
  api.post('/addNotification', function (req, res) {

    var token = req.body.authtoken || req.params.authtoken || req.headers.authtoken;

    commonService.addNotificationService(req.body,token, function (response) {
        res.send(response);
    });

  });


  //Add edit VideoCall
  api.post('/addVideoCall', function (req, res) {

    var token = req.body.authtoken || req.params.authtoken || req.headers.authtoken;

    commonService.addVideoCallService(req.body,token, function (response) {
        res.send(response);
    });

  });


  //Add edit User Specialization Button
  api.post('/addEditUserSpecialization', function (req, res) {

    var token = req.body.authtoken || req.params.authtoken || req.headers.authtoken;

    commonService.addEditUserSpecialization(req.body,token, function (response) {
        res.send(response);
    });

  });


api.get('/get-terms-and-condition', function (req, res) {
    var adminData = req.body;
    commonService.getTermsAndConditionsService(adminData, function (response) {
         res.send(response);
    });
})
api.post('/edit-terms-and-condition', function (req, res) {
    var adminData = req.body;
    commonService.editTermsAndConditionsService(adminData, function (response) {
        res.send(response);
    });
})



module.exports = api;